### ISSUE TITLE
After Installation Process

### ISSUE THREAD

**Issue by JorgeDDW** [bonsaiERP/bonsaiERP#5]
This is what I get:
```
Puma caught this error: Missing `secret_token` and `secret_key_base` for 'development' environment, set these values in `config/secrets.yml` (RuntimeError)
/Users/Jorge/.rvm/gems/ruby-2.3.1@bonsai/gems/railties-4.2.5.1/lib/rails/application.rb:534:in `validate_secret_key_config!'
/Users/Jorge/.rvm/gems/ruby-2.3.1@bonsai/gems/railties-4.2.5.1/lib/rails/application.rb:246:in `env_config'
/Users/Jorge/.rvm/gems/ruby-2.3.1@bonsai/gems/railties-4.2.5.1/lib/rails/engine.rb:514:in `call'
/Users/Jorge/.rvm/gems/ruby-2.3.1@bonsai/gems/railties-4.2.5.1/lib/rails/application.rb:165:in `call'
/Users/Jorge/.rvm/gems/ruby-2.3.1@bonsai/gems/railties-4.2.5.1/lib/rails/railtie.rb:194:in `public_send'
/Users/Jorge/.rvm/gems/ruby-2.3.1@bonsai/gems/railties-4.2.5.1/lib/rails/railtie.rb:194:in `method_missing'
/Users/Jorge/.rvm/gems/ruby-2.3.1@global/gems/rack-1.6.4/lib/rack/deflater.rb:35:in `call'
/Users/Jorge/.rvm/gems/ruby-2.3.1@global/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
/Users/Jorge/.rvm/gems/ruby-2.3.1@bonsai/gems/puma-3.4.0/lib/puma/configuration.rb:224:in `call'
/Users/Jorge/.rvm/gems/ruby-2.3.1@bonsai/gems/puma-3.4.0/lib/puma/server.rb:569:in `handle_request'
/Users/Jorge/.rvm/gems/ruby-2.3.1@bonsai/gems/puma-3.4.0/lib/puma/server.rb:406:in `process_client'
/Users/Jorge/.rvm/gems/ruby-2.3.1@bonsai/gems/puma-3.4.0/lib/puma/server.rb:271:in `block in run'
/Users/Jorge/.rvm/gems/ruby-2.3.1@bonsai/gems/puma-3.4.0/lib/puma/thread_pool.rb:114:in `block in spawn_thread'
```

**Comment by boriscy** [comment]
I will look later, thanks for informing

**Comment by boriscy** [comment]
You shloud create secrets file
http://guides.rubyonrails.org/4_1_release_notes.html#config-secrets-yml

**Comment by JorgeDDW** [comment]
that work good!

First time working with sass, i dont have the knowledge, can you guide me through this?
but now i facing this part: 

```

DEPRECATION WARNING on line 87 of /Users/Jorge/.rvm/gems/ruby-2.3.1@bonsai/gems/compass-core-1.0.3/stylesheets/compass/css3/_deprecated-support.scss: #{} interpolation near operators will be simplified
in a future version of Sass. To preserve the current behavior, use quotes:

  unquote('"$moz-"#{$experimental-support-for-mozilla} "$webkit-"#{$experimental-support-for-webkit} "$opera-"#{$experimental-support-for-opera} "$microsoft-"#{$experimental-support-for-microsoft} "$khtml-"#{$experimental-support-for-khtml}')

You can use the sass-convert command to automatically fix most cases.


DEPRECATION WARNING on line 92 of /Users/Jorge/.rvm/gems/ruby-2.3.1@bonsai/gems/compass-core-1.0.3/stylesheets/compass/css3/_deprecated-support.scss: #{} interpolation near operators will be simplified
in a future version of Sass. To preserve the current behavior, use quotes:

  unquote('"$ie6-"#{$legacy-support-for-ie6} "$ie7-"#{$legacy-support-for-ie7} "$ie8-"#{$legacy-support-for-ie8}')

You can use the sass-convert command to automatically fix most cases.


WARNING on line 253 of /Users/Jorge/Desktop/projects/bonsaiERP/app/assets/stylesheets/components/forms.sass.erb:
This selector doesn't have any properties and will not be rendered.

WARNING on line 226 of /Users/Jorge/Desktop/projects/bonsaiERP/app/assets/stylesheets/components/ui.sass:
This selector doesn't have any properties and will not be rendered.
```

**Comment by JorgeDDW** [comment]
I solved the issue on #https://github.com/bonsaiERP/bonsaiERP/issues/5#issuecomment-230098811 

But i Got this now...

Sass::SyntaxError at /
Undefined variable: "$green".
  (in /Users/Jorge/Desktop/projects/bonsaiERP/app/assets/stylesheets/plugins/icons.css.sass:18)

**Comment by boriscy** [comment]
Can you change the line 1 of that file to `@import 'colors'` you might have to change the imports, since it looks that you have an updated version of sass

**Comment by JorgeDDW** [comment]
Same error. @boriscy
